version: '3'

networks:
  my-network:
    driver: bridge

services:

  db:
    image: postgres:16-alpine
    restart: always
    container_name: uni-db

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5454:5432'
    networks:
      - my-network

  web:
    build:
      context: .
    container_name: uni-bot
    command: python main.py run
    volumes:
      - .:/app
    env_file:
      - .env