[tool.poetry]
name = "university-bot"
version = "0.1.0"
description = ""
authors = ["ivalukyan <ivalukyanov@gmail.com>"]
license = "LICENSE"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
